version: '2'
services:

  library-backend:
    image: devplant/library-backend
    restart: always
    ports:
      - 7000:7000
    environment:
      - VIRTUAL_HOST=*/api/*
      - VIRTUAL_HOST_WEIGHT=1

